"""Excel and PPTX generation from a validated agent.AgentAnalysis."""

import os

from openpyxl import Workbook
from openpyxl.styles import Alignment, Font
from openpyxl.utils import get_column_letter
from pptx import Presentation
from pptx.util import Inches

from app.services.agent import AgentAnalysis
from app.services.portfolio import EnrichedHolding

EXPORTS_DIR = os.path.join(os.path.dirname(os.path.dirname(os.path.dirname(__file__))), "exports")

HOLDINGS_HEADERS = [
    "Ticker",
    "Quantity",
    "Buy Price",
    "Current Price",
    "Cost Basis",
    "Market Value",
    "Gain/Loss",
    "Gain/Loss %",
    "Allocation %",
]


def _exports_dir() -> str:
    os.makedirs(EXPORTS_DIR, exist_ok=True)
    return EXPORTS_DIR


def _f(value) -> float | None:
    return float(value) if value is not None else None


def generate_excel(run_id: int, analysis: AgentAnalysis, holdings: list[EnrichedHolding]) -> str:
    wb = Workbook()

    overview = wb.active
    overview.title = "Overview"
    overview["A1"] = "PortfolioPilot — Risk Analysis"
    overview["A1"].font = Font(bold=True, size=14)

    overview["A3"] = "Overview"
    overview["A3"].font = Font(bold=True)
    overview["A4"] = analysis.overview
    overview["A4"].alignment = Alignment(wrap_text=True)
    overview.merge_cells("A4:E6")

    row = 8
    overview.cell(row=row, column=1, value="Risk Flags").font = Font(bold=True)
    row += 1
    for flag in analysis.risk_flags:
        overview.cell(row=row, column=1, value=f"• {flag}")
        row += 1

    row += 1
    overview.cell(row=row, column=1, value="Diversification Note").font = Font(bold=True)
    row += 1
    overview.cell(row=row, column=1, value=analysis.diversification_note)
    overview.cell(row=row, column=1).alignment = Alignment(wrap_text=True)
    overview.merge_cells(f"A{row}:E{row + 2}")

    for col, width in zip("ABCDE", [50, 20, 20, 20, 20]):
        overview.column_dimensions[col].width = width

    holdings_ws = wb.create_sheet("Holdings")
    holdings_ws.append(HOLDINGS_HEADERS)
    for cell in holdings_ws[1]:
        cell.font = Font(bold=True)
    for e in holdings:
        holdings_ws.append(
            [
                e.holding.ticker,
                _f(e.holding.quantity),
                _f(e.holding.buy_price),
                _f(e.current_price),
                _f(e.cost_basis),
                _f(e.market_value),
                _f(e.gain_loss),
                _f(e.gain_loss_pct),
                _f(e.allocation_pct),
            ]
        )
    for idx, header in enumerate(HOLDINGS_HEADERS, start=1):
        holdings_ws.column_dimensions[get_column_letter(idx)].width = max(14, len(header) + 2)

    commentary_ws = wb.create_sheet("Top Holdings Commentary")
    commentary_ws.append(["Ticker", "Commentary"])
    for cell in commentary_ws[1]:
        cell.font = Font(bold=True)
    for item in analysis.top_holdings_commentary:
        commentary_ws.append([item.ticker, item.commentary])
    commentary_ws.column_dimensions["A"].width = 12
    commentary_ws.column_dimensions["B"].width = 90

    path = os.path.join(_exports_dir(), f"run_{run_id}.xlsx")
    wb.save(path)
    return path


def generate_pptx(run_id: int, analysis: AgentAnalysis, holdings: list[EnrichedHolding]) -> str:
    prs = Presentation()
    bullet_layout = prs.slide_layouts[1]

    title_slide = prs.slides.add_slide(prs.slide_layouts[0])
    title_slide.shapes.title.text = "Portfolio Risk Analysis"
    title_slide.placeholders[1].text = f"Generated by PortfolioPilot — Run #{run_id}"

    overview_slide = prs.slides.add_slide(bullet_layout)
    overview_slide.shapes.title.text = "Overview"
    overview_slide.placeholders[1].text_frame.text = analysis.overview

    risk_slide = prs.slides.add_slide(bullet_layout)
    risk_slide.shapes.title.text = "Risk Flags"
    tf = risk_slide.placeholders[1].text_frame
    flags = analysis.risk_flags or ["No risk flags identified."]
    tf.text = flags[0]
    for flag in flags[1:]:
        tf.add_paragraph().text = flag

    diversification_slide = prs.slides.add_slide(bullet_layout)
    diversification_slide.shapes.title.text = "Diversification"
    diversification_slide.placeholders[1].text_frame.text = analysis.diversification_note

    table_slide = prs.slides.add_slide(prs.slide_layouts[5])
    table_slide.shapes.title.text = "Holdings Allocation"
    rows = len(holdings) + 1
    cols = 4
    table_shape = table_slide.shapes.add_table(
        rows, cols, Inches(0.5), Inches(1.5), Inches(9), Inches(0.4 * rows)
    )
    table = table_shape.table
    for col, header in enumerate(["Ticker", "Market Value", "Gain/Loss %", "Allocation %"]):
        table.cell(0, col).text = header
    for r, e in enumerate(holdings, start=1):
        table.cell(r, 0).text = e.holding.ticker
        table.cell(r, 1).text = f"${e.market_value:,.2f}" if e.market_value is not None else "N/A"
        table.cell(r, 2).text = f"{e.gain_loss_pct:.1f}%" if e.gain_loss_pct is not None else "N/A"
        table.cell(r, 3).text = f"{e.allocation_pct:.1f}%" if e.allocation_pct is not None else "N/A"

    commentary_slide = prs.slides.add_slide(bullet_layout)
    commentary_slide.shapes.title.text = "Top Holdings Commentary"
    tf = commentary_slide.placeholders[1].text_frame
    commentary = analysis.top_holdings_commentary
    if commentary:
        tf.text = f"{commentary[0].ticker}: {commentary[0].commentary}"
        for item in commentary[1:]:
            tf.add_paragraph().text = f"{item.ticker}: {item.commentary}"
    else:
        tf.text = "No commentary available."

    path = os.path.join(_exports_dir(), f"run_{run_id}.pptx")
    prs.save(path)
    return path
